const API_BASE_URL_DEVELOPMENT = 'https://localhost:7237';
const API_BASE_URL_PRODUCTION = 'https://appname.azurewebsites.net';

const ENDPOINTS = {
    LOGIN: 'login',
    LOGOUT: 'logout',
    REGISTER: 'register',

    GET_ALL_EXERCISES_TYPE: 'get-all-exercise-type',
    GET_EXERCISE_TYPE_BY_ID: 'get-exercise-type-by-id',
    CREATE_EXERCISE_TYPE: 'create-exercise-type',
    UPDATE_EXERCISE_TYPE: 'update-exercise-type',
    DELETE_EXERCISE_TYPE_BY_ID: 'delete-exercise-type-by-id',

    GET_ALL_EXERCISES: 'get-all-exercise',
    GET_EXERCISE_BY_ID: 'get-exercise-by-id',
    CREATE_EXERCISE: 'create-exercise',
    UPDATE_EXERCISE: 'update-exercise',
    DELETE_EXERCISE_BY_ID: 'delete-exercise-by-id',

    GET_ALL_MUSCLE_GROUP: 'get-all-muscle-group',
    GET_MUSCLE_GROUP_BY_ID: 'get-muscle-group-by-id',
    CREATE_MUSCLE_GROUP: 'create-muscle-group',
    UPDATE_MUSCLE_GROUP: 'update-muscle-group',
    DELETE_MUSCLE_GROUP_BY_ID: 'delete-muscle-group-by-id',

    GET_ALL_ROLES: 'get-all-roles',
    GET_ALL_USER_ROLES: 'get-all-user-roles',

    GET_ALL_SET: 'get-all-set',
    GET_SET_BY_ID: 'get-set-by-id',
    CREATE_SET: 'create-set',
    UPDATE_SET: 'update-set',
    DELETE_SET_BY_ID: 'delete-set-by-id',

    GET_ALL_USER: 'get-all-user',
    GET_USER_BY_ID: 'get-user-by-id',
    UPDATE_USER: 'update-user',
    DELETE_USER_BY_ID: 'delete-user-by-id',
    ADD_USER_ROLE: 'add-user-role',

    GET_ALL_WORKOUT: 'get-all-workout',
    GET_WORKOUT_BY_ID: 'get-workout-by-id',
    CREATE_WORKOUT: 'create-workout',
    UPDATE_WORKOUT: 'update-workout',
    DELETE_WORKOUT_BY_ID: 'delete-workout-by-id'
};

const development = {
    API_URL_LOGIN: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.LOGIN}`,
    API_URL_LOGOUT: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.LOGOUT}`,
    API_URL_REGISTER: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.REGISTER}`,

    API_URL_GET_ALL_EXERCISES_TYPE: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_ALL_EXERCISES_TYPE}`,
    API_URL_GET_EXERCISE_TYPE_BY_ID: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_EXERCISE_TYPE_BY_ID}`,
    API_URL_CREATE_EXERCISE_TYPE: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.CREATE_EXERCISE_TYPE}`,
    API_URL_UPDATE_EXERCISE_TYPE: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.UPDATE_EXERCISE_TYPE}`,
    API_URL_DELETE_EXERCISE_TYPE_BY_ID: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.DELETE_EXERCISE_TYPE_BY_ID}`,

    API_URL_GET_ALL_EXERCISES: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_ALL_EXERCISES}`,
    API_URL_GET_EXERCISE_BY_ID: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_EXERCISE_BY_ID}`,
    API_URL_CREATE_EXERCISE: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.CREATE_EXERCISE}`,
    API_URL_UPDATE_EXERCISE: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.UPDATE_EXERCISE}`,
    API_URL_DELETE_EXERCISE_BY_ID: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.DELETE_EXERCISE_BY_ID}`,

    API_URL_GET_ALL_MUSCLE_GROUP: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_ALL_MUSCLE_GROUP}`,
    API_URL_GET_MUSCLE_GROUP_BY_ID: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_MUSCLE_GROUP_BY_ID}`,
    API_URL_CREATE_MUSCLE_GROUP: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.CREATE_MUSCLE_GROUP}`,
    API_URL_UPDATE_MUSCLE_GROUP: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.UPDATE_MUSCLE_GROUP}`,
    API_URL_DELETE_MUSCLE_GROUP_BY_ID: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.DELETE_MUSCLE_GROUP_BY_ID}`,

    API_URL_GET_ALL_ROLES: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_ALL_ROLES}`,
    API_URL_GET_ALL_USER_ROLES: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_ALL_USER_ROLES}`,

    API_URL_GET_ALL_SET: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_ALL_SET}`,
    API_URL_GET_SET_BY_ID: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_SET_BY_ID}`,
    API_URL_CREATE_SET: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.CREATE_SET}`,
    API_URL_UPDATE_SET: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.UPDATE_SET}`,
    API_URL_DELETE_SET_BY_ID: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.DELETE_SET_BY_ID}`,

    API_URL_GET_ALL_USER: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_ALL_USER}`,
    API_URL_GET_USER_BY_ID: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_USER_BY_ID}`,
    API_URL_UPDATE_USER: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.UPDATE_USER}`,
    API_URL_DELETE_USER_BY_ID: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.DELETE_USER_BY_ID}`,
    API_URL_ADD_USER_ROLE: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.ADD_USER_ROLE}`,

    API_URL_GET_ALL_WORKOUT: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_ALL_WORKOUT}`,
    API_URL_GET_WORKOUT_BY_ID: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_WORKOUT_BY_ID}`,
    API_URL_CREATE_WORKOUT: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.CREATE_WORKOUT}`,
    API_URL_UPDATE_WORKOUT: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.UPDATE_WORKOUT}`,
    API_URL_DELETE_WORKOUT_BY_ID: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.DELETE_WORKOUT_BY_ID}`
};

const production = {
    API_URL_LOGIN: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.LOGIN}`,
    API_URL_LOGOUT: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.LOGOUT}`,
    API_URL_REGISTER: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.REGISTER}`,

    API_URL_GET_ALL_EXERCISES_TYPE: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.GET_ALL_EXERCISES_TYPE}`,
    API_URL_GET_EXERCISE_TYPE_BY_ID: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.GET_EXERCISE_TYPE_BY_ID}`,
    API_URL_CREATE_EXERCISE_TYPE: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.CREATE_EXERCISE_TYPE}`,
    API_URL_UPDATE_EXERCISE_TYPE: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.UPDATE_EXERCISE_TYPE}`,
    API_URL_DELETE_EXERCISE_TYPE_BY_ID: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.DELETE_EXERCISE_TYPE_BY_ID}`,

    API_URL_GET_ALL_EXERCISES: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.GET_ALL_EXERCISES}`,
    API_URL_GET_EXERCISE_BY_ID: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.GET_EXERCISE_BY_ID}`,
    API_URL_CREATE_EXERCISE: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.CREATE_EXERCISE}`,
    API_URL_UPDATE_EXERCISE: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.UPDATE_EXERCISE}`,
    API_URL_DELETE_EXERCISE_BY_ID: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.DELETE_EXERCISE_BY_ID}`,

    API_URL_GET_ALL_MUSCLE_GROUP: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.GET_ALL_MUSCLE_GROUP}`,
    API_URL_GET_MUSCLE_GROUP_BY_ID: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.GET_MUSCLE_GROUP_BY_ID}`,
    API_URL_CREATE_MUSCLE_GROUP: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.CREATE_MUSCLE_GROUP}`,
    API_URL_UPDATE_MUSCLE_GROUP: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.UPDATE_MUSCLE_GROUP}`,
    API_URL_DELETE_MUSCLE_GROUP_BY_ID: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.DELETE_MUSCLE_GROUP_BY_ID}`,

    API_URL_GET_ALL_ROLES: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.GET_ALL_ROLES}`,
    API_URL_GET_ALL_USER_ROLES: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.GET_ALL_USER_ROLES}`,

    API_URL_GET_ALL_SET: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.GET_ALL_SET}`,
    API_URL_GET_SET_BY_ID: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.GET_SET_BY_ID}`,
    API_URL_CREATE_SET: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.CREATE_SET}`,
    API_URL_UPDATE_SET: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.UPDATE_SET}`,
    API_URL_DELETE_SET_BY_ID: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.DELETE_SET_BY_ID}`,

    API_URL_GET_ALL_USER: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.GET_ALL_USER}`,
    API_URL_GET_USER_BY_ID: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.GET_USER_BY_ID}`,
    API_URL_UPDATE_USER: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.UPDATE_USER}`,
    API_URL_DELETE_USER_BY_ID: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.DELETE_USER_BY_ID}`,
    API_URL_ADD_USER_ROLE: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.ADD_USER_ROLE}`,

    API_URL_GET_ALL_WORKOUT: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.GET_ALL_WORKOUT}`,
    API_URL_GET_WORKOUT_BY_ID: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.GET_WORKOUT_BY_ID}`,
    API_URL_CREATE_WORKOUT: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.CREATE_WORKOUT}`,
    API_URL_UPDATE_WORKOUT: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.UPDATE_WORKOUT}`,
    API_URL_DELETE_WORKOUT_BY_ID: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.DELETE_WORKOUT_BY_ID}`
};

const Constants = process.env.NODE_ENV === 'development' ? development : production;
export default Constants;
